name: machine_dashboard
description: "A robust and well-structured Flutter application for machine management and job handling."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  qr_flutter: ^4.1.0
  fl_chart: ^0.68.0
  clock: ^1.1.1
  # flutter_launcher_icons should be a dev_dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5       # For testing BLoCs
  mockito: ^5.4.4          # For creating mock objects
  build_runner: ^2.4.7     # For running mockito's code generator

  # Moved this from dependencies, as it's a development tool
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  # 1. The 'assets' section lists your images.
  assets:
    - assets/machine_icon.png
    - assets/arcpilot_icon.png
    - assets/cigweld_icon.png
    - assets/weld_icon.png


  fonts:
    - family: Kallisto  # This is the name you will use in your Dart code.
      fonts:
        - asset: assets/fonts/kallisto_Thin.ttf

# --- ADD THIS CONFIGURATION BLOCK ---
# This block configures the flutter_launcher_icons package
flutter_launcher_icons:
  android: true
  ios: true
  # Set this path to your main, high-resolution app icon
  # I've used one from your assets list as an example.
  image_path: "assets/app_icon.png"
  # You can also add platform-specific overrides if needed
  # android: "assets/android_icon.png"
  # ios: "assets/ios_icon.png"
